version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - echo Installing hugo
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.92.0/hugo_extended_0.92.0_Linux-64bit.deb
      - dpkg -i hugo.deb

  pre_build:
    commands:
      - echo In pre_build phase..
      - echo Current environment is $ENV
      - cp config-${ENV}.toml config.toml
      - echo End of the pre_build phase..

  build:
    commands:
      - hugo --minify
      - hugo deploy